EASYOPAC-1115 - Added font, variables and other config files.
easySuite/Kulture_Theme pull request #1
Opened 2019-09-09 07:58 UTC by mihaelad

2019-12-19 12:30 UTC, NicolaeGrigoriu commented on scripts/kulture.js
> +  $(document).ready(function () {
Here can be used drupal behaviours: https://www.drupal.org/node/756722#behaviors

2019-12-19 12:31 UTC, NicolaeGrigoriu commented on scripts/kulture.js
> +
based on drupal coding standards, add new line at the end of the file

2019-12-19 12:32 UTC, NicolaeGrigoriu commented on scss/components/_event-details.scss
> +.event-details-wrapper {
add proper indendation for all scss files.

2019-12-19 12:32 UTC, NicolaeGrigoriu commented on scss/mixins/_checkbox.scss
> +}
add new line at the end of the file.

2019-12-19 12:34 UTC, NicolaeGrigoriu commented on scripts/kulture.js
> +    console.log(listContainerRef);
is this line necessary?

2019-12-19 12:38 UTC, NicolaeGrigoriu requested changes
There are some changes to be made in the scss files and js

2020-02-17 10:02 UTC, NicolaeGrigoriu requested changes

2020-02-17 10:02 UTC, NicolaeGrigoriu commented on scripts/materials.js
> +      console.log($('.field-type-ting-reference > .field-items', context),'---')
is this needed?

2020-02-17 10:02 UTC, NicolaeGrigoriu commented on scss/components/_library-arrangementer.scss
> +    .pane-og-menu-og-single-menu-block h2 a {
is scss file shouldn't this single selector?

2020-02-17 10:02 UTC, NicolaeGrigoriu commented on scss/components/_library-details.scss
> +    .panel-pane-inner h2.pane-title a {
shouldn't here be a single selector in scss file?

2020-02-17 10:02 UTC, NicolaeGrigoriu commented on scss/fonts/_fortuna.scss
> +  //   url('../fonts/Fortuna Regular.otf') format('opentype');
are the comments required?

2020-02-17 10:02 UTC, NicolaeGrigoriu commented on scss/fonts/_rubik.scss
> +  // url('../fonts/Rubik-Regular.otf') format('opentype');
are the comments required?

2020-02-17 10:02 UTC, NicolaeGrigoriu commented on templates/node/node--ding-event.tpl.php
> +
are the new lines needed in this tpl file?

2020-02-17 11:50 UTC, mihaelad commented on scss/components/_library-details.scss
> +    .panel-pane-inner h2.pane-title a {
On the culture site are 3 different menu but the styles are identical and this why is need these selector

2020-02-17 11:56 UTC, mihaelad commented on scss/fonts/_fortuna.scss
> +  //   url('../fonts/Fortuna Regular.otf') format('opentype');
To work the fonts in all of browsers are required all of this formats which are committed. I expect them from the customer.

2020-02-17 11:56 UTC, mihaelad commented on scss/fonts/_rubik.scss
> +  // url('../fonts/Rubik-Regular.otf') format('opentype');
To work the fonts in all of browsers are required all of this formats which are committed. I expect them from the customer.

2020-02-18 07:49 UTC, merged